name: POI-API

on:
  push:
    branches: [ master ]
    paths: 
      - apis/poi/**
      - .github/workflows/POI-API.yml
  pull_request:
    branches: [ master ]
    paths:
      - apis/poi/**
      - .github/workflows/POI-API.yml

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      #with:
        #dotnet-version: 3.1.301
    - name: Install dependencies 
      run: dotnet restore apis/poi/web/*.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore apis/poi/web/*.csproj
    - name: Unit Tests
      run: dotnet build --configuration Release apis/poi/tests/UnitTests/UnitTests.csproj
    - name: Test
      run: dotnet test --no-restore --verbosity normal apis/poi/tests/UnitTests

    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUBTOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            assignees: [ '${{ github.actor }}' ],
            body: 'POI Build failed'
          });
